config/routes.rb
Rails.application.routes.draw do

 	resources :posts do 
	    member do 
	      get :review
	      get :publish
	    end
	end
	resources :topics
	devise_for :users, path: '', path_names: { sign_in: 'adminLogin'}, skip: [:registration] do
	  get '/users/sign_out' => 'devise/sessions#destroy'
	end

	get 'about-product', to: 'static#about'
	get 'static/contact'	
	root to: 'static#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :topic
	has_rich_text :body
	enum status: {draft: 0, review: 1, publish: 2}

	def self.published_by_order
		order("updated_at DESC")
	end

	def self.published
		where(status: "publish")
	end
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin], multiple: false)                                               ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :review, :publish]
  access all: [:index, :show], user: :all

  # GET /posts
  def index
    if current_user.present?
      @posts = Post.published_by_order
    else
      @posts = Post.published_by_order.published
    end
    @topics = Topic.all
  end

  # GET /posts/1
  def show
    @topics = Topic.all
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.topic_id = 1 
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully destroyed.'
  end


  def review
    @post.review!
    redirect_to request.referrer 
  end

  def publish
    @post.publish!
    redirect_to request.referrer 
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def post_params
      params.require(:post).permit(:title, :body, :status, :topic_id)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  	if current_user.present?
      @posts = Post.published_by_order.limit(3)
    else
      @posts = Post.published_by_order.published.limit(3)
    end
    @topics = Topic.all
  end

  def about
  end

  def contact
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController


  def index
    @topics = Topic.all
  end

  def show
    @topics = Topic.all
    @topic = Topic.find(params[:id])
    if current_user.present?
  	  @posts = @topic.posts.published_by_order
    else
      @posts = @topic.posts.published_by_order.published
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prodinpro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">  
    <link rel="stylesheet" type="text/css" href="trix.css">
    <script type="text/javascript" src="trix.js"></script> 
    <meta charset="utf-8">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <%= yield %>
    </div>
      <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_blogauthor.html.erb
<div class="card  p-3 m-5 shadow-sm">
  <div class="row no-gutters">
    <div class="col-md-4">
	  <div class="u-lg-avatar">
	  	<%= image_tag "https://i.imgur.com/YcP0tikb.jpg", class: "img-fluid rounded-circle", alt: "Office Office" %> 
	  </div>  
	</div>
    <div class="col-md-8">
      <div class="card-body">
    <small class="d-block text-muted text-uppercase">Written by</small>
    <h3 class="h5 font-weight-medium mb-0"><a href="blog-profile.html">Hanna Wolfe</a> </h3>
    <p class="mb-0">I create advanced website builders made exclusively for web developers.</p>
    <p class="h6 font-weight-normal">Follow us on <a class="link-muted" href="#">Medium</a>, <a class="link-muted" href="#">Twitter</a>, <a class="link-muted" href="#">Facebook</a>, <a class="link-muted" href="#">YouTube</a>, and <a class="link-muted" href="#">Dribbble</a>.</p>
      </div>
    </div>
  </div>
</div>

app/views/posts/_blogbody.html.erb
<div class="container my-5">
	<h1 class="text-center"><%= @post.title %> </h1>
</div>
<%= render "blogshare" %>
<div class="my-5 ">
	<p> <%= @post.body %> </p>
</div>

app/views/posts/_blogshare.html.erb
<div class="border-bottom pb-2 mb-2">
    <div class="row align-items-md-center">
      <div class="col-md-7 mb-5 mb-md-0">
        <span class="d-block text-muted font-italic"> 
          Published on: <%= @post.updated_at.strftime("%d/%m/%Y")%> in <span class="topic_badge"> <%= link_to @post.topic.title, topic_path(@post.topic) %> </span></span>
       </div>
    <div class="col-md-5">
      <div class="d-md-flex justify-content-md-end align-items-md-center">
        <h4 class="text-secondary font-weight-medium ">Share:</h4>

        <a class="btn btn-sm btn-icon btn-soft-secondary btn-bg-transparent rounded-circle ml-2" href="#">
          <span class="fab fa-facebook-f btn-icon__inner"></span>
        </a>
        <a class="btn btn-sm btn-icon btn-soft-secondary btn-bg-transparent rounded-circle ml-2" href="#">
          <span class="fab fa-twitter btn-icon__inner"></span>
        </a>
        <a class="btn btn-sm btn-icon btn-soft-secondary btn-bg-transparent rounded-circle ml-2" href="#">
          <span class="fab fa-instagram btn-icon__inner"></span>
        </a>
        <a class="btn btn-sm btn-icon btn-soft-secondary btn-bg-transparent rounded-circle ml-2" href="#">
          <span class="fab fa-telegram btn-icon__inner"></span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/posts/_blogsubscribe.html.erb
<div class="card bg-info text-white text-center p-5 m-5">
  <h4 class="mb-3">Like what you're reading? Subscribe to our top stories.</h4> 
    <!-- Form -->
    <form class=" mt-3 js-validate w-md-75 mx-md-auto">
      <div class="js-form-message">
        <div class="d-flex align-items-center">
          <label class="sr-only" for="subscribeSrArticle">Subscribe</label>
          <div class="input-group">
            <input type="email" class="form-control" name="email" id="subscribeSrArticle" placeholder="Your email" aria-label="Your email" required
                   data-msg="Please enter a valid email address."
                   data-error-class="u-has-error"
                   data-success-class="u-has-success">
          </div>
          <button type="submit" class="btn btn-light ml-3">Submit</button>

        </div>
      </div>
    </form>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.rich_text_area :body, cols: "200", class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :topic %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                selected: post.topic_id,
                                include_blank: true
                              },
                              class: 'form-control'
                            )
    %>
  </div>

  <div class="form-group">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_relatedarticles.html.erb
<div class="container">
  <div class="w-lg-75 border-top space-2 mx-lg-auto">
    <div class="mb-5">
      <h3 class="font-weight-medium">Related stories</h3>
    </div>

    <div class="row">
      <div class="col-md-6">
        <!-- Blog Card -->
        <article class="border-bottom h-100 py-5">
          <div class="row justify-content-between">
            <div class="col-6">
              <a class="d-inline-block text-muted font-weight-medium text-uppercase small" href="#">Product</a>
              <h4 class="h6 font-weight-medium mb-0">
                <a href="single-article.html">InVision design forward fund</a>
              </h4>
            </div>

            <div class="col-5">
              <img class="img-fluid" src="../../assets/img/500x280/img18.jpg" alt="Image Description">
            </div>
          </div>
        </article>
        <!-- End Blog Card -->
      </div>

      <div class="col-md-6">
        <!-- Blog Card -->
        <article class="border-bottom h-100 py-5">
          <div class="row justify-content-between">
            <div class="col-6">
              <a class="d-inline-block text-muted font-weight-medium text-uppercase small" href="#">Business</a>
              <h4 class="h6 font-weight-medium mb-0">
                <a href="single-article.html">What CFR really is about</a>
              </h4>
            </div>

            <div class="col-5">
              <img class="img-fluid" src="../../assets/img/500x280/img13.jpg" alt="Image Description">
            </div>
          </div>
        </article>
        <!-- End Blog Card -->
      </div>

      <div class="col-md-6">
        <!-- Blog Card -->
        <article class="border-bottom h-100 py-5">
          <div class="row justify-content-between">
            <div class="col-6">
              <a class="d-inline-block text-muted font-weight-medium text-uppercase small" href="#">Front academy</a>
              <h4 class="h6 font-weight-medium mb-0">
                <a href="single-article.html">What is KYC and why do we need it</a>
              </h4>
            </div>

            <div class="col-5">
              <img class="img-fluid" src="../../assets/img/500x280/img24.jpg" alt="Image Description">
            </div>
          </div>
        </article>
        <!-- End Blog Card -->
      </div>

      <div class="col-md-6">
        <!-- Blog Card -->
        <article class="border-bottom h-100 py-5">
          <div class="row justify-content-between">
            <div class="col-6">
              <a class="d-inline-block text-muted font-weight-medium text-uppercase small" href="#">Business</a>
              <h4 class="h6 font-weight-medium mb-0">
                <a href="single-article.html">Enjoy $1,000 worth of perks with Front for Business</a>
              </h4>
            </div>

            <div class="col-5">
              <img class="img-fluid" src="../../assets/img/500x280/img19.jpg" alt="Image Description">
            </div>
          </div>
        </article>
        <!-- End Blog Card -->
      </div>
    </div>
  </div>
</div>
<!-- End Blog Card Section -->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', root_path %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render "shared/navbar" %>

<p class="index-title"> Updates and Articles </p>
<%= render "shared/blogcards" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<%= render "shared/navbar" %>
<%= render "shared/admincontrols" %>
<%= render "blogbody" %>
<%= render "blogsubscribe" %>

<div class="border-top py-3 my-3">
  <%= render "blogshare" %>
</div>
<%= render "blogauthor" %>

app/views/shared/_admincontrols.html.erb
<% if current_user.present? %>
  <div class="btn-group">
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary btn-sm" %>
    <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm" %>
	</div>
	<span> 
    <% if @post.status == 'draft' %> 
    	<%= link_to 'Schedule for review', review_post_path(@post) ,class: "btn btn-warning  btn-sm" %>
    <% elsif @post.status == 'review' %>
    	<%= link_to 'Publish the post', publish_post_path(@post) ,class: "btn btn-success  btn-sm" %>
    <% end%>	
    </span>
<% end %>

app/views/shared/_blogcards.html.erb
<div class="row">
  <div class="col-md-10"> 
    <div class="row">
      <% @posts.each do |post| %>
          <div class="col-sm-12 col-md-6 mb-5">
            <div class="card border-0 shadow-soft h-100">
              <div class="card-body p-5">
                <div class="blog-index-title">
                  <%= truncate(post.title, length:40, separator: ' ') %>
                </div>
                <p class="mb-0"> <%= truncate(strip_tags(post.body.to_s), length: 200, separator: ' ') %> </p>
                <span class="blog-post-meta"> Published <%= distance_of_time_in_words(post.updated_at , Time.now) %> in <span class="topic_badge"> <%= link_to post.topic.title, topic_path(post.topic) %> </span></span>
              </div>
              <div class="card-footer bg-light border-0 py-4 px-5">
                <% if current_user.present? %>
                    <span class="badge badge-secondary">
                    <% if post.status== 'draft' %> 
                      Draft
                    <% elsif post.status== 'review' %>
                      Review Pending
                    <% else %>
                      Published
                    <% end%>  
                    </span>
                <% end %>
                <%= link_to post do %>
                  Continue reading <%= image_tag("/assets/next.svg") %> 
                <% end %>  
              </div>
            </div>
      </div>
      <% end %>
    </div>
  </div>
  <%= render "shared/blogsidebar" %>
</div>

app/views/shared/_blogsidebar.html.erb
<aside class="col-md-2 bg-white">
	<div class="blog-sidebar">
	  <div class="p-4">
	    <h4 class="font-italic">Elsewhere</h4>
	    <ol class="list-unstyled">
	      <li><a href="#">GitHub</a></li>
	      <li><a href="#">Twitter</a></li>
	      <li><a href="#">Facebook</a></li>
	    </ol>
	  </div>
	</div>
</aside>

app/views/shared/_footer.html.erb
<footer class="blog-footer">
</footer>

app/views/shared/_header.html.erb
<header class="blog-header p-3 sticky-top">
  <div class="container">  
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4">
        <%= link_to "Product in Progress", root_path, class: "blog-header-logo text-dark" %>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <% if current_user.present? %>
        <div class="btn-group">
          <%= link_to 'New Post', new_post_path, class: "btn btn-outline-info" %>
          <%= link_to "Logout", destroy_user_session_path, class: "btn btn-outline-danger" %>
        </div>
        <% else %>
          Subscribe
        <% end %>
      </div>
  </div>
  </div>
</header>

app/views/shared/_navbar.html.erb
<div class="nav-scroller py-3 mb-2 ">
  <nav class="nav d-flex justify-content-between">
  	<% @topics.each do |topic| %>
  		<%= link_to topic.title, topic_path(topic), class: "text-muted" %>
    <% end %>	
  </nav>
</div>

app/views/topics/index.html.erb
<%= render "shared/navbar" %>
<% @topics.each do |topic| %>
  <%= link_to topic.title, topic %>
<% end %>     

app/views/topics/show.html.erb
<%= render "shared/navbar" %>
<div class="container my-5">
	<h1 class="text-center"><%= @topic.title %> </h1>
</div>
<%= render "shared/blogcards" %>